import { useState } from 'react';
import { api, mediaUrl, type EditorContent, type Entry, type Media, type VideoValue } from './api';
import { AssetPicker, Check, Feedback, Field, ImageField } from './fields';

export function emptyContent(collection: 'projects' | 'notes'): EditorContent {
  return collection === 'projects' ? { title: '', slug: '', summary: '', description: [''], published: false, featured: false, order: 100, images: [], features: [], technologies: [], openToCollaborators: false, relatedLinks: [] } : { kind: 'original', title: '', slug: '', summary: '', published: false, date: new Date().toISOString().slice(0, 10), category: '', tags: [], body: [''] };
}
function normalized(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(normalized).filter((item) => item !== undefined);
  if (value && typeof value === 'object') return Object.fromEntries(Object.entries(value).map(([key, item]) => [key, normalized(item)]).filter(([, item]) => item !== undefined));
  return value === '' ? undefined : value;
}
export function Editor({ collection, initial, media, onUpload, onSaved, onClose }: { collection: 'projects' | 'notes'; initial?: Entry<EditorContent>; media: Media[]; onUpload: (asset: Media) => void; onSaved: (entry: Entry<EditorContent>) => void; onClose: () => void }) {
  const [content, setContent] = useState<EditorContent>(initial?.content || emptyContent(collection));
  const [entry, setEntry] = useState(initial); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [busy, setBusy] = useState(false); const [preview, setPreview] = useState(false);
  const update = <K extends keyof EditorContent>(key: K, value: EditorContent[K]) => { setContent((previous) => ({ ...previous, [key]: value })); setSuccess(''); };
  const paragraphs = (key: 'description' | 'story' | 'technicalDescription' | 'body', label: string, required = false) => <Field label={label} multiline required={required} value={content[key]?.join('\n\n')} onChange={(value) => update(key, value ? value.split(/\n\s*\n/) : undefined)} />;
  const lines = (key: 'technologies' | 'nextSteps' | 'tags', label: string) => <Field label={label} multiline value={content[key]?.join('\n')} onChange={(value) => update(key, value ? value.split('\n') : undefined)} />;
  async function save(event: React.FormEvent) {
    event.preventDefault(); setBusy(true); setError(''); setSuccess('');
    try {
      const saved = await api<Entry<EditorContent>>(`/${collection}${entry ? `/${entry.id}` : ''}`, entry ? 'PUT' : 'POST', { content: normalized(content), ...(entry ? { version: entry.version } : {}) });
      setEntry(saved); setContent(saved.content); onSaved(saved); setSuccess(saved.content.published ? 'Published. The public site will show this update on its next request.' : 'Draft saved. This entry is not public.');
    } catch (error) { setError((error as Error).message); } finally { setBusy(false); }
  }
  return <section className="editor"><div className="toolbar"><h2>{entry ? 'Edit' : 'Create'} {collection === 'projects' ? 'project' : 'note'}</h2><button type="button" className="quiet" onClick={onClose}>Back to list</button></div>
    <form onSubmit={save}>
      <fieldset><legend>Essentials</legend>{collection === 'notes' && <label>Note type<select value={content.kind} onChange={(event) => { const kind = event.target.value as 'original' | 'external'; setContent((previous) => { const next = { ...previous, kind }; if (kind === 'original') { delete next.source; delete next.externalUrl; delete next.myComment; next.body = ['']; } else { delete next.body; next.source = ''; next.externalUrl = ''; next.myComment = ''; } return next; }); }}><option value="original">Original note</option><option value="external">External reference</option></select></label>}
        <Field label="Title" required value={content.title} onChange={(value) => update('title', value)} /><Field label="Slug" required value={content.slug} onChange={(value) => update('slug', value)} /><Field label="Summary / excerpt" multiline required value={content.summary} onChange={(value) => update('summary', value)} />
        <Check label="Published" value={content.published} onChange={(value) => update('published', value)} />
        {collection === 'projects' ? <><Check label="Featured on homepage" value={content.featured} onChange={(value) => update('featured', value)} /><Field label="Display order (lower first)" type="number" value={String(content.order ?? 100)} onChange={(value) => update('order', Number(value))} /><label>Status<select value={content.status || ''} onChange={(event) => update('status', event.target.value || undefined)}><option value="">Not specified</option>{['Active', 'Exploring', 'Open to Collaborators', 'Maintained', 'Archived'].map((status) => <option key={status}>{status}</option>)}</select></label></> : <><Field label="Publish date" type="date" required value={content.date} onChange={(value) => update('date', value)} /><Field label="Category" required value={content.category} onChange={(value) => update('category', value)} />{lines('tags', 'Tags (one per line)')}</>}
      </fieldset>
      <ImageField label="Cover image" value={collection === 'projects' ? content.coverImage : content.image} onChange={(value) => update(collection === 'projects' ? 'coverImage' : 'image', value)} media={media} onUpload={onUpload} />
      {collection === 'notes' ? <fieldset><legend>{content.kind === 'original' ? 'Your writing' : 'External reference'}</legend>{content.kind === 'original' ? paragraphs('body', 'Body (blank lines separate paragraphs)', true) : <><Field label="Source / publication" required value={content.source} onChange={(value) => update('source', value)} /><Field label="External URL" type="url" required value={content.externalUrl} onChange={(value) => update('externalUrl', value)} /><Field label="My comment / why I shared this" multiline required value={content.myComment} onChange={(value) => update('myComment', value)} /></>}</fieldset> : <>
        <fieldset><legend>The project story</legend>{paragraphs('description', 'Overview (blank lines separate paragraphs)', true)}{paragraphs('story', 'Why it exists / story')}{paragraphs('technicalDescription', 'How it works (optional)')}{lines('technologies', 'Technologies (one per line)')}<Field label="Live URL" type="url" value={content.liveUrl} onChange={(value) => update('liveUrl', value)} /><Field label="Repository URL" type="url" value={content.repositoryUrl} onChange={(value) => update('repositoryUrl', value)} /><Field label="Current status" multiline value={content.currentStatus} onChange={(value) => update('currentStatus', value)} />{lines('nextSteps', 'Next steps (one per line)')}<Field label="Started date" type="date" value={content.startedAt} onChange={(value) => update('startedAt', value)} /><Field label="Updated date" type="date" value={content.updatedAt} onChange={(value) => update('updatedAt', value)} /><Field label="Content completeness note (optional)" multiline value={content.contentNote} onChange={(value) => update('contentNote', value)} /></fieldset>
        <fieldset><legend>Screenshots</legend>{(content.images || []).map((image, index) => <div className="repeat-row" key={`${index}-${image.src}`}><ImageField label={`Screenshot ${index + 1}`} value={image} media={media} onUpload={onUpload} onChange={(value) => update('images', value ? content.images!.map((item, i) => i === index ? value : item) : content.images!.filter((_, i) => i !== index))} /><div className="row-actions"><button type="button" className="quiet" disabled={index === 0} onClick={() => { const images = [...content.images!]; [images[index - 1], images[index]] = [images[index], images[index - 1]]; update('images', images); }}>Move screenshot {index + 1} up</button></div></div>)}<AssetPicker label="screenshot" media={media} accept="image" onUpload={onUpload} onSelect={(asset) => update('images', [...(content.images || []), { src: asset.url, alt: '', width: asset.width!, height: asset.height! }])} /></fieldset>
        <fieldset><legend>Features</legend>{(content.features || []).map((feature, index) => <div className="repeat-row" key={index}><Field label={`Feature ${index + 1} title`} value={feature.title} onChange={(value) => update('features', content.features!.map((item, i) => i === index ? { ...item, title: value } : item))} /><Field label={`Feature ${index + 1} description`} multiline value={feature.description} onChange={(value) => update('features', content.features!.map((item, i) => i === index ? { ...item, description: value } : item))} /><ImageField label={`Feature ${index + 1} image`} value={feature.image} media={media} onUpload={onUpload} onChange={(value) => update('features', content.features!.map((item, i) => i === index ? { ...item, image: value } : item))} /><button type="button" className="quiet" onClick={() => update('features', content.features!.filter((_, i) => i !== index))}>Remove feature {index + 1}</button></div>)}<button type="button" className="quiet" onClick={() => update('features', [...(content.features || []), { title: '', description: '' }])}>Add feature</button></fieldset>
        <fieldset><legend>Optional video</legend><label>Video type<select value={content.video?.kind || ''} onChange={(event) => update('video', event.target.value === 'file' ? { kind: 'file', src: '', caption: '', transcript: '' } : event.target.value === 'external' ? { kind: 'external', url: '', caption: '' } : undefined)}><option value="">No video</option><option value="file">Uploaded video</option><option value="external">External video link</option></select></label>{content.video && <VideoFields value={content.video} onChange={(value) => update('video', value)} media={media} onUpload={onUpload} />}</fieldset>
        <fieldset><legend>Collaboration</legend><Check label="Open to collaborators" value={content.openToCollaborators} onChange={(value) => update('openToCollaborators', value)} />{content.openToCollaborators && <Field label="Collaboration description" multiline required value={content.collaborationDescription} onChange={(value) => update('collaborationDescription', value)} />}</fieldset>
        <fieldset><legend>Related links</legend>{(content.relatedLinks || []).map((link, index) => <div className="repeat-row" key={index}><Field label={`Link ${index + 1} label`} value={link.label} onChange={(value) => update('relatedLinks', content.relatedLinks!.map((item, i) => i === index ? { ...item, label: value } : item))} /><Field label={`Link ${index + 1} URL`} type="url" value={link.url} onChange={(value) => update('relatedLinks', content.relatedLinks!.map((item, i) => i === index ? { ...item, url: value } : item))} /><button type="button" className="quiet" onClick={() => update('relatedLinks', content.relatedLinks!.filter((_, i) => i !== index))}>Remove link {index + 1}</button></div>)}<button type="button" className="quiet" onClick={() => update('relatedLinks', [...(content.relatedLinks || []), { label: '', url: '' }])}>Add related link</button></fieldset>
      </>}
      <Feedback error={error} success={success} /><div className="editor-actions"><button type="submit" disabled={busy}>{busy ? 'Saving…' : `Save ${collection === 'projects' ? 'project' : 'note'}`}</button><button type="button" className="quiet" onClick={() => setPreview(!preview)}>{preview ? 'Close preview' : 'Preview content'}</button></div>
    </form>{preview && <ContentPreview content={content} />}
  </section>;
}
function VideoFields({ value, onChange, media, onUpload }: { value: VideoValue; onChange: (value: VideoValue) => void; media: Media[]; onUpload: (asset: Media) => void }) {
  return <><Field label="Video caption" value={value.caption} onChange={(caption) => onChange({ ...value, caption })} />{value.kind === 'external' ? <><Field label="Video URL" type="url" value={value.url} onChange={(url) => onChange({ ...value, url })} /><ImageField label="Video poster" value={value.poster} media={media} onUpload={onUpload} onChange={(poster) => onChange({ ...value, poster })} /></> : <><AssetPicker label="video" media={media} accept="video" onUpload={onUpload} onSelect={(asset) => onChange({ ...value, src: asset.url })} />{value.src && <p>Video selected.</p>}<Field label="Video transcript" multiline value={value.transcript} onChange={(transcript) => onChange({ ...value, transcript })} /><AssetPicker label="video poster" media={media} accept="image" onUpload={onUpload} onSelect={(asset) => onChange({ ...value, poster: asset.url })} />{value.poster && <p>Poster selected. <button type="button" className="quiet" onClick={() => onChange({ ...value, poster: undefined })}>Remove poster</button></p>}<AssetPicker label="captions" media={media} accept="captions" onUpload={onUpload} onSelect={(asset) => onChange({ ...value, captions: asset.url })} />{value.captions && <p>Captions selected. <button type="button" className="quiet" onClick={() => onChange({ ...value, captions: undefined })}>Remove captions</button></p>}</>}</>;
}
function ContentPreview({ content }: { content: EditorContent }) {
  const cover = content.coverImage || content.image;
  return <section className="content-preview" aria-label="Content preview"><p className="eyebrow">Preview — not a public page</p><h2>{content.title}</h2><p>{content.summary}</p>{cover && <img src={mediaUrl(cover.src)} alt={cover.alt} />}{[...(content.description || []), ...(content.body || []), ...(content.story || [])].map((paragraph, i) => <p key={i}>{paragraph}</p>)}{content.kind === 'external' && <><p>{content.myComment}</p><p>{content.source} · External link</p></>}{content.images?.map((image, i) => <figure key={i}><img src={mediaUrl(image.src)} alt={image.alt} /><figcaption>{image.caption}</figcaption></figure>)}{content.features?.map((feature, i) => <div key={i}><h3>{feature.title}</h3><p>{feature.description}</p>{feature.image && <img src={mediaUrl(feature.image.src)} alt={feature.image.alt} />}</div>)}{content.video?.kind === 'file' && content.video.src && <video src={mediaUrl(content.video.src)} controls preload="none" />}{content.currentStatus && <p>{content.currentStatus}</p>}{content.openToCollaborators && <p>{content.collaborationDescription}</p>}</section>;
}
