import { useEffect, useState } from 'react';
import { allItems, api, mediaUrl, type Entry, type Media } from './api';
import { AssetPicker, Check, Feedback, Field } from './fields';

type Current = { label: string; text: string; href: string; visible: boolean; order: number };
export function Currently() {
  const [entries, setEntries] = useState<Entry<Current>[]>([]); const [error, setError] = useState('');
  useEffect(() => { allItems<Entry<Current>>('/currently').then(setEntries).catch((error) => setError(error.message)); }, []);
  return <><p>Hidden items stay private. Visible items need text.</p><Feedback error={error} />{['Building', 'Reading', 'Exploring', 'Open to'].map((label, order) => <CurrentEditor key={entries.find((entry) => entry.content.label === label)?.id || label} initial={entries.find((entry) => entry.content.label === label)} label={label} order={order} />)}</>;
}
function CurrentEditor({ initial, label, order }: { initial?: Entry<Current>; label: string; order: number }) {
  const [entry, setEntry] = useState(initial); const [content, setContent] = useState<Current>(initial?.content || { label, text: '', href: '', visible: false, order });
  const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [busy, setBusy] = useState(false);
  return <form onSubmit={async (event) => { event.preventDefault(); setBusy(true); setError(''); setSuccess(''); try { const saved = await api<Entry<Current>>(`/currently${entry ? `/${entry.id}` : ''}`, entry ? 'PUT' : 'POST', { content, ...(entry ? { version: entry.version } : {}) }); setEntry(saved); setSuccess('Saved.'); } catch (error) { setError((error as Error).message); } finally { setBusy(false); } }}><fieldset><legend>{label}</legend><Field label={`${label} text`} multiline value={content.text} onChange={(text) => setContent({ ...content, text })} /><Field label={`${label} link (HTTPS or /#contact)`} value={content.href} onChange={(href) => setContent({ ...content, href })} /><Check label={`Show ${label}`} value={content.visible} onChange={(visible) => setContent({ ...content, visible })} /><Feedback error={error} success={success} /><button disabled={busy}>Save {label}</button></fieldset></form>;
}

type Message = { id: string; name: string; email?: string; subject: string; preview?: string; message?: string; status: 'unread' | 'read' | 'archived'; createdAt: string };
export function Inbox() {
  const [messages, setMessages] = useState<Message[]>([]); const [selected, setSelected] = useState<Message>(); const [filter, setFilter] = useState('all'); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  useEffect(() => { allItems<Message>('/messages').then(setMessages).catch((error) => setError(error.message)).finally(() => setLoading(false)); }, []);
  async function status(value: Message['status']) {
    if (!selected) return;
    try { await api(`/messages/${selected.id}`, 'PATCH', { status: value }); setSelected({ ...selected, status: value }); setMessages((items) => items.map((item) => item.id === selected.id ? { ...item, status: value } : item)); } catch (error) { setError((error as Error).message); }
  }
  return <><Feedback error={error} />{loading && <p role="status">Loading messages…</p>}{selected ? <article><button className="quiet" onClick={() => setSelected(undefined)}>Back to inbox</button><h2>{selected.subject || 'No subject'}</h2><p>{selected.name} · <a href={`mailto:${selected.email}`}>{selected.email}</a></p><p>{new Date(selected.createdAt).toLocaleString()} · {selected.status}</p><p className="message-body">{selected.message}</p><div className="row-actions"><button onClick={() => status('read')}>Mark read</button><button className="quiet" onClick={() => status('unread')}>Mark unread</button><button className="quiet" onClick={() => status('archived')}>Archive</button></div></article> : <><label>Filter messages<select value={filter} onChange={(event) => setFilter(event.target.value)}>{['all', 'unread', 'read', 'archived'].map((value) => <option key={value}>{value}</option>)}</select></label>{!loading && !messages.length && <p>No messages yet.</p>}<div className="entry-list">{messages.filter((item) => filter === 'all' || item.status === filter).map((item) => <article key={item.id}><div><h2>{item.subject || 'No subject'}</h2><p>{item.name} · {item.status} · {new Date(item.createdAt).toLocaleString()}</p><p>{item.preview}</p></div><button className="quiet" onClick={async () => { try { setSelected(await api<Message>(`/messages/${item.id}`)); } catch (error) { setError((error as Error).message); } }}>Open message</button></article>)}</div></>}</>;
}

export function MediaLibrary() {
  const [media, setMedia] = useState<Media[]>([]); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  useEffect(() => { allItems<Media>('/media').then(setMedia).catch((error) => setError(error.message)).finally(() => setLoading(false)); }, []);
  return <><p>Uploads are private until referenced by published content. Referenced files cannot be deleted.</p><Feedback error={error} />{(['image', 'video', 'captions'] as const).map((type) => <AssetPicker key={type} label={type} accept={type} media={[]} onSelect={() => {}} onUpload={(asset) => setMedia((items) => [asset, ...items])} />)}{loading && <p role="status">Loading media…</p>}{!loading && !media.length && <p>No uploads yet.</p>}<div className="cards">{media.map((asset) => <article key={asset.id}>{asset.mimeType.startsWith('image/') && <img loading="lazy" src={mediaUrl(asset.url)} alt={asset.originalName} />}<h2>{asset.originalName}</h2><p>{asset.mimeType} · {Math.ceil(asset.size / 1024)} KB</p><button className="quiet danger" onClick={async () => { if (!window.confirm(`Permanently delete “${asset.originalName}”?`)) return; try { await api(`/media/${asset.id}`, 'DELETE'); setMedia((items) => items.filter((item) => item.id !== asset.id)); } catch (error) { setError((error as Error).message); } }}>Delete media</button></article>)}</div></>;
}

type SiteSettings = { name: string; description: string; email: string; hero: { eyebrow: string; thought: string; introduction: string }; about: string[]; social: { label: string; url: string }[] };
export function Settings() {
  const [data, setData] = useState<{ content: SiteSettings; version: number }>(); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [busy, setBusy] = useState(false);
  useEffect(() => { api<{ content: SiteSettings; version: number }>('/settings').then(setData).catch((error) => setError(error.message)); }, []);
  if (!data?.content) return <><Feedback error={error} /><p>Site settings are unavailable. Run the backend seed command for initial content.</p></>;
  const content = data.content;
  const update = (patch: Partial<SiteSettings>) => { setData({ ...data, content: { ...content, ...patch } }); setSuccess(''); };
  return <form onSubmit={async (event) => { event.preventDefault(); setBusy(true); setError(''); setSuccess(''); try { setData(await api('/settings', 'PUT', data)); setSuccess('Settings saved.'); } catch (error) { setError((error as Error).message); } finally { setBusy(false); } }}><fieldset><legend>Public identity and copy</legend><Field label="Display name" required value={content.name} onChange={(name) => update({ name })} /><Field label="Site description" required multiline value={content.description} onChange={(description) => update({ description })} /><Field label="Contact email" type="email" required value={content.email} onChange={(email) => update({ email })} />{(['eyebrow', 'thought', 'introduction'] as const).map((key) => <Field key={key} label={`Hero ${key}`} required multiline={key === 'introduction'} value={content.hero[key]} onChange={(value) => update({ hero: { ...content.hero, [key]: value } })} />)}<Field label="About (blank lines separate paragraphs)" multiline required value={content.about.join('\n\n')} onChange={(value) => update({ about: value.split(/\n\s*\n/) })} /></fieldset><fieldset><legend>Social links</legend>{content.social.map((link, index) => <div className="repeat-row" key={index}><Field label={`Social ${index + 1} label`} required value={link.label} onChange={(label) => update({ social: content.social.map((item, i) => i === index ? { ...item, label } : item) })} /><Field label={`Social ${index + 1} URL`} type="url" required value={link.url} onChange={(url) => update({ social: content.social.map((item, i) => i === index ? { ...item, url } : item) })} /><button type="button" className="quiet" onClick={() => update({ social: content.social.filter((_, i) => i !== index) })}>Remove link {index + 1}</button></div>)}<button type="button" className="quiet" onClick={() => update({ social: [...content.social, { label: '', url: '' }] })}>Add social link</button></fieldset><Feedback error={error} success={success} /><button disabled={busy}>{busy ? 'Saving…' : 'Save settings'}</button></form>;
}
